/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davidde' at '2/6/16 1:19 PM' with Gradle 2.10
 *
 * @author davidde, @date 2/6/16 1:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
